
# =============================================================================
# 03_pbmc_normalization_and_ranking.R
#
# PURPOSE
# Combines bulk maternal PBMC ATAC-seq accessibility with the single-cell
# PBMC reference summary, computes PBMC-normalized accessibility ratios,
# ranks the 52 placenta-associated genes by normalized contribution score,
# generates the PBMC-normalized ranking figure, and exports the top-ranked
# subset.
#
# INPUTS
# - panel_bulkPBMC_signal_df:
#   Per-sample, per-gene bulk PBMC ATAC-seq accessibility across
#   gene-centered +/- 10 kb windows. This object is generated by
#   01_quantify_accessibility.R.
#
# - panel_scPBMC_summary:
#   Per-gene single-cell PBMC reference accessibility summary, including
#   scPBMC_max_no_other. This object is generated by
#   02_scPBMC_reference_quantification.R.
#
# OUTPUTS
# - Supplementary_Table_S9_bulk_vs_scPBMC_per_sample.csv
# - Supplementary_Table_S10_panel_gene_contribution.csv
# - Figure2C_panel_gene_contribution_ranking.png
# - Table1_top_ranked_subset.csv
#
# DEPENDENCIES
# dplyr, ggplot2
# =============================================================================

library(dplyr)
library(ggplot2)

# =============================================================================
# 1. Combine bulk PBMC signal with single-cell PBMC reference summary
# =============================================================================

panel_bulkPBMC_vs_scPBMC <- merge(
  panel_bulkPBMC_signal_df,
  panel_scPBMC_summary,
  by = "gene",
  all.x = TRUE
)

# =============================================================================
# 2. Compute PBMC-normalized accessibility ratios
# =============================================================================
# For each gene in each maternal PBMC sample, bulk +/- 10 kb accessibility
# is divided by the gene's maximum accessibility across retained single-cell
# PBMC immune groups. A small constant is added to the denominator to avoid
# division by zero.

panel_bulkPBMC_vs_scPBMC$mean_over_scPBMCmax <-
  panel_bulkPBMC_vs_scPBMC$mean_signal /
  (panel_bulkPBMC_vs_scPBMC$scPBMC_max_no_other + 1e-6)

panel_bulkPBMC_vs_scPBMC$max_over_scPBMCmax <-
  panel_bulkPBMC_vs_scPBMC$max_signal /
  (panel_bulkPBMC_vs_scPBMC$scPBMC_max_no_other + 1e-6)

# =============================================================================
# 3. Save combined per-sample bulk versus scPBMC table
# =============================================================================

write.csv(
  panel_bulkPBMC_vs_scPBMC,
  file = "Supplementary_Table_S9_bulk_vs_scPBMC_per_sample.csv",
  row.names = FALSE
)

# =============================================================================
# 4. Aggregate to per-gene contribution ranking
# =============================================================================

panel_gene_contribution <- panel_bulkPBMC_vs_scPBMC |>
  dplyr::group_by(gene) |>
  dplyr::summarise(
    mean_bulkPBMC_signal    = mean(mean_signal, na.rm = TRUE),
    mean_over_scPBMCmax     = mean(mean_over_scPBMCmax, na.rm = TRUE),
    mean_max_over_scPBMCmax = mean(max_over_scPBMCmax, na.rm = TRUE),
    .groups = "drop"
  ) |>
  dplyr::arrange(
    dplyr::desc(mean_over_scPBMCmax),
    dplyr::desc(mean_max_over_scPBMCmax)
  )

# =============================================================================
# 5. Save per-gene PBMC-normalized contribution ranking table
# =============================================================================

write.csv(
  as.data.frame(panel_gene_contribution),
  file = "Supplementary_Table_S10_panel_gene_contribution.csv",
  row.names = FALSE
)

# =============================================================================
# 6. Generate Figure 2C: PBMC-normalized contribution ranking
# =============================================================================

plot_panel_gene_contribution <- as.data.frame(panel_gene_contribution)

plot_panel_gene_contribution$gene <- factor(
  plot_panel_gene_contribution$gene,
  levels = rev(plot_panel_gene_contribution$gene)
)

p_panel_gene_contribution <- ggplot(
  plot_panel_gene_contribution,
  aes(x = gene, y = mean_over_scPBMCmax)
) +
  geom_col() +
  coord_flip() +
  theme_bw() +
  labs(
    title = "Trophoblast/placenta-associated gene contribution ranking",
    x = "Gene",
    y = "Mean bulk PBMC / scPBMC-max ratio"
  )

ggsave(
  filename = "Figure2C_panel_gene_contribution_ranking.png",
  plot = p_panel_gene_contribution,
  width = 5.5,
  height = 10.2,
  units = "in",
  dpi = 300
)

# =============================================================================
# 7. Define top-ranked subset
# =============================================================================

top_contributing_genes <- panel_gene_contribution$gene[1:10]

top_contributing_gene_table <- as.data.frame(
  panel_gene_contribution[
    panel_gene_contribution$gene %in% top_contributing_genes,
  ]
)

# =============================================================================
# 8. Save top-ranked subset table
# =============================================================================

write.csv(
  top_contributing_gene_table,
  file = "Table1_top_ranked_subset.csv",
  row.names = FALSE
)

# =============================================================================
## Objects required by 04_permutation_validation.R:
# - panel_bulkPBMC_vs_scPBMC
# - panel_gene_contribution
# - top_contributing_genes
# - top_contributing_gene_table
# =============================================================================
