# PURPOSE
# Evaluates reproducibility and statistical enrichment of the top-ranked
# PBMC-normalized placenta-associated gene subset. This script generates
# sample-level and gene-level summaries, a Z-score-normalized accessibility
# heatmap, a permutation test comparing the top-ranked subset against random
# same-sized gene subsets, and a full-panel versus top-ranked subset comparison.
#
# INPUTS
# - panel_bulkPBMC_signal_df:
#   Per-sample, per-gene bulk PBMC ATAC-seq accessibility across
#   gene-centered +/- 10 kb windows. This object is generated by
#   01_quantify_accessibility.R.
#
# - panel_bulkPBMC_vs_scPBMC:
#   Per-sample bulk PBMC accessibility combined with scPBMC reference values.
#   This object is generated by 03_pbmc_normalization_and_ranking.R.
#
# - top_contributing_genes:
#   Character vector containing the top ten PBMC-normalized genes. This object
#   is generated by 03_pbmc_normalization_and_ranking.R.
#
# OUTPUTS
# - Supplementary_Table_S11_top_gene_sample_summary.csv
# - Supplementary_Table_S12_permutation_null_summary.csv
# - Supplementary_Table_S13_panel_vs_top_compare.csv
# - Figure3A_reproducibility_heatmap.png
# - Figure3B_sample_level.png
# - Figure3C_gene_level.png
# - Figure3D_empirical_null.png
# - Figure3E_panel_vs_top.png
#
# DEPENDENCIES
# dplyr, ggplot2

library(dplyr)
library(ggplot2)

# 1. Build validation dataset for the top-ranked genes


top_gene_level_df <- subset(
  panel_bulkPBMC_vs_scPBMC,
  gene %in% top_contributing_genes
)

# 2. Generate sample-level summary for the top-ranked subset

top_gene_sample_summary <- top_gene_level_df |>
  dplyr::group_by(sample) |>
  dplyr::summarise(
    mean_bulkPBMC_signal    = mean(mean_signal, na.rm = TRUE),
    mean_over_scPBMCmax     = mean(mean_over_scPBMCmax, na.rm = TRUE),
    mean_max_over_scPBMCmax = mean(max_over_scPBMCmax, na.rm = TRUE),
    .groups = "drop"
  )

write.csv(
  as.data.frame(top_gene_sample_summary),
  file = "Supplementary_Table_S11_top_gene_sample_summary.csv",
  row.names = FALSE
)


# 3. Generate Figure 3A: Z-score heatmap of top-ranked genes


heatmap_df <- panel_bulkPBMC_signal_df |>
  dplyr::filter(gene %in% top_contributing_genes) |>
  dplyr::select(gene, sample, mean_signal) |>
  dplyr::group_by(gene) |>
  dplyr::mutate(
    z_signal = (mean_signal - mean(mean_signal, na.rm = TRUE)) /
      sd(mean_signal, na.rm = TRUE)
  ) |>
  dplyr::ungroup()

heatmap_df$gene <- factor(
  heatmap_df$gene,
  levels = rev(top_contributing_genes)
)

heatmap_df$sample <- factor(
  heatmap_df$sample,
  levels = c(
    "ATAC_Batch2_023B",
    "ATAC_Batch2_039B",
    "ATAC_Batch2_040B",
    "ATAC_Batch2_049B"
  ),
  labels = c("023B", "039B", "040B", "049B")
)

p_fig3a <- ggplot(
  heatmap_df,
  aes(x = sample, y = gene, fill = z_signal)
) +
  geom_tile(color = "white", linewidth = 0.5) +
  scale_fill_gradient2(
    low = "#2166AC",
    mid = "white",
    high = "#B2182B",
    midpoint = 0,
    name = "Z-score\n(accessibility)"
  ) +
  theme_bw(base_size = 11) +
  labs(
    title = "Reproducibility of +/- 10 kb accessibility across bulk PBMC samples",
    x = "Bulk PBMC sample",
    y = "Top-ranked genes"
  ) +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank()
  )

ggsave(
  filename = "Figure3A_reproducibility_heatmap.png",
  plot = p_fig3a,
  width = 7,
  height = 5.5,
  dpi = 300
)


# 4. Generate Figure 3B: sample-level PBMC-normalized accessibility

p_fig3b <- ggplot(
  top_gene_sample_summary,
  aes(x = sample, y = mean_over_scPBMCmax, group = 1)
) +
  geom_point(size = 3) +
  geom_line(linewidth = 0.8) +
  theme_bw() +
  labs(
    title = "Top-ranked subset: sample-level bulk PBMC / scPBMC-max ratio",
    x = "Bulk PBMC sample",
    y = "Mean bulk PBMC / scPBMC-max ratio"
  )

ggsave(
  filename = "Figure3B_sample_level.png",
  plot = p_fig3b,
  width = 9,
  height = 6,
  units = "in",
  dpi = 300
)

# 5. Generate Figure 3C: gene-level PBMC-normalized accessibility

plot_top_gene_level_df <- top_gene_level_df

plot_top_gene_level_df$gene <- factor(
  plot_top_gene_level_df$gene,
  levels = rev(unique(top_contributing_genes))
)

p_fig3c <- ggplot(
  plot_top_gene_level_df,
  aes(x = gene, y = mean_over_scPBMCmax)
) +
  geom_jitter(width = 0.12, height = 0, size = 2.5, alpha = 0.9) +
  coord_flip() +
  theme_bw() +
  labs(
    title = "Top-ranked subset: gene-level bulk PBMC / scPBMC-max ratio",
    x = "Gene",
    y = "Mean bulk PBMC / scPBMC-max ratio"
  )

ggsave(
  filename = "Figure3C_gene_level.png",
  plot = p_fig3c,
  width = 9,
  height = 7,
  units = "in",
  dpi = 300
)


# 6. Build per-gene PBMC-normalized values for the full panel

gene_universe_df <- panel_bulkPBMC_vs_scPBMC |>
  dplyr::group_by(gene) |>
  dplyr::summarise(
    mean_over_scPBMCmax = mean(mean_over_scPBMCmax, na.rm = TRUE),
    .groups = "drop"
  )


# 7. Run permutation test

set.seed(42)

observed_top_mean_ratio <- mean(
  gene_universe_df$mean_over_scPBMCmax[
    gene_universe_df$gene %in% top_contributing_genes
  ],
  na.rm = TRUE
)

n_top_genes <- length(top_contributing_genes)
n_perm <- 10000
null_top_mean_ratios <- numeric(n_perm)

for (i in seq_len(n_perm)) {
  random_genes <- sample(
    gene_universe_df$gene,
    size = n_top_genes,
    replace = FALSE
  )
  null_top_mean_ratios[i] <- mean(
    gene_universe_df$mean_over_scPBMCmax[
      gene_universe_df$gene %in% random_genes
    ],
    na.rm = TRUE
  )
}

empirical_p_top_mean <- (
  sum(null_top_mean_ratios >= observed_top_mean_ratio) + 1
) / (length(null_top_mean_ratios) + 1)


# 8. Save permutation summary table

top_gene_null_table <- data.frame(
  metric = c(
    "observed_top_mean_over_scPBMCmax",
    "null_mean",
    "null_median",
    "null_sd",
    "null_q025",
    "null_q25",
    "null_q75",
    "null_q975",
    "null_max",
    "n_perm_ge_observed",
    "empirical_p_top_mean"
  ),
  value = c(
    observed_top_mean_ratio,
    mean(null_top_mean_ratios),
    median(null_top_mean_ratios),
    sd(null_top_mean_ratios),
    quantile(null_top_mean_ratios, 0.025),
    quantile(null_top_mean_ratios, 0.25),
    quantile(null_top_mean_ratios, 0.75),
    quantile(null_top_mean_ratios, 0.975),
    max(null_top_mean_ratios),
    sum(null_top_mean_ratios >= observed_top_mean_ratio),
    empirical_p_top_mean
  )
)

write.csv(
  top_gene_null_table,
  file = "Supplementary_Table_S12_permutation_null_summary.csv",
  row.names = FALSE
)


# 9. Generate Figure 3D: empirical null distribution

null_top_df <- data.frame(null_mean_ratio = null_top_mean_ratios)

p_fig3d <- ggplot(null_top_df, aes(x = null_mean_ratio)) +
  geom_histogram(bins = 40, color = "black", fill = "grey80") +
  geom_vline(xintercept = observed_top_mean_ratio, linewidth = 1, color = "red") +
  theme_bw() +
  labs(
    title = "Empirical null for the top-ranked subset",
    x = "Mean bulk PBMC / scPBMC-max ratio of random same-sized gene sets",
    y = "Count"
  )

ggsave(
  filename = "Figure3D_empirical_null.png",
  plot = p_fig3d,
  width = 9,
  height = 6,
  units = "in",
  dpi = 300
)


# 10. Build full-panel versus top-ranked subset comparison


panel_summary <- panel_bulkPBMC_vs_scPBMC |>
  dplyr::group_by(sample) |>
  dplyr::summarise(
    group                   = "Full_panel",
    mean_bulkPBMC_signal    = mean(mean_signal, na.rm = TRUE),
    mean_over_scPBMCmax     = mean(mean_over_scPBMCmax, na.rm = TRUE),
    mean_max_over_scPBMCmax = mean(max_over_scPBMCmax, na.rm = TRUE),
    .groups = "drop"
  )

top_gene_summary <- top_gene_level_df |>
  dplyr::group_by(sample) |>
  dplyr::summarise(
    group                   = "Top_ranked_subset",
    mean_bulkPBMC_signal    = mean(mean_signal, na.rm = TRUE),
    mean_over_scPBMCmax     = mean(mean_over_scPBMCmax, na.rm = TRUE),
    mean_max_over_scPBMCmax = mean(max_over_scPBMCmax, na.rm = TRUE),
    .groups = "drop"
  )

panel_vs_top_compare <- rbind(panel_summary, top_gene_summary)

write.csv(
  as.data.frame(panel_vs_top_compare),
  file = "Supplementary_Table_S13_panel_vs_top_compare.csv",
  row.names = FALSE
)


# 11. Generate Figure 3E: full panel versus top-ranked subset

p_fig3e <- ggplot(
  panel_vs_top_compare,
  aes(x = sample, y = mean_over_scPBMCmax, color = group, group = group)
) +
  geom_point(size = 3) +
  geom_line(linewidth = 0.8) +
  theme_bw() +
  labs(
    title = "Full panel vs top-ranked subset",
    x = "Bulk PBMC sample",
    y = "Mean bulk PBMC / scPBMC-max ratio",
    color = "Group"
  )

ggsave(
  filename = "Figure3E_panel_vs_top.png",
  plot = p_fig3e,
  width = 11,
  height = 7,
  units = "in",
  dpi = 300
)
